import { orderMessages } from './orderMessages';
import { createI18n } from 'vue-i18n';
export const messages = {
  'zh-Hans': {
    orders: orderMessages['zh-Hans'],
    pagination: { previous: '上一页', next: '下一页', page: '第 {page} 页' },
    brand: 'Smilelab', tagline: '连接门诊、医生与患者', workspace: 'DSO 工作台', demo: '开发演示 · 请使用测试资料', loginTitle: '进入工作台', loginDescription: '使用单独交付的员工开发凭证。', identity: '演示账号', staffKey: '员工开发密钥', login: '登录', logout: '退出', language: 'English', clinic: '当前门诊', refresh: '刷新', save: '保存', create: '创建', cancel: '取消', close: '关闭', loading: '正在加载', empty: '暂无记录', error: '操作未完成', networkError: '网络请求失败，请检查连接后重试。', doctor: '医生', manager: '门诊经理', consultant: '咨询顾问', operator: '平台运维', nav: { orders: '共享订单', appointments: '预约与排班', patients: '患者档案', crm: '咨询与跟进', operations: '集成与审计' },
    appointments: { tooMany: '当前日期区间超过1000条预约，请切换到较短的日期视图。', title: '预约与排班', description: '查看门诊预约，管理医生可预约时段。', newSlot: '新增时段', start: '开始时间', end: '结束时间', doctor: '医生', patient: '患者', time: '预约时间', status: '状态', action: '操作', slots: '可预约时段', schedule: '排班日历', arrive: '登记到诊', complete: '完成预约', noShow: '标记未到', cancel: '取消预约', timezone: '时间按当前设备时区显示；提交时包含时区。' },
    patients: { title: '患者档案', description: '医生仅查看患者授权的临床资料。', name: '姓名', created: '建档时间', open: '查看档案', records: '临床病历', newRecord: '新建病历', complaint: '主诉', history: '病史', examination: '检查', assessment: '评估', plan: '计划', draft: '草稿', signed: '已签署', sign: '签署病历', signPrompt: '签署后不可覆盖原记录。确认内容完整后签署。', amendment: '创建修订', edit: '编辑草稿', teeth: '牙位记录（FDI）', permanent: '恒牙', primary: '乳牙', tooth: '牙位', finding: '牙位备注', removeTooth: '移除牙位备注', noAccess: '当前角色可查看基本目录，临床资料需医生和患者授权。', select: '从左侧选择患者', previous: '修订原记录', version: '版本', recordsDescription: '已签署病历通过新记录修订，保留原文。' },
    crm: { title: '咨询与跟进', description: '管理牙科咨询线索及后续联系，临床正文独立保存。', newLead: '新增线索', titleField: '线索标题', stage: '阶段', created: '创建时间', open: '查看跟进', activities: '跟进记录', newActivity: '新增跟进', summary: '跟进摘要', due: '计划时间', type: '类型', finish: '完成跟进', call: '电话联系', follow_up: '后续联系', visit: '到店沟通', boundary: '商业集成只发送生成的引用，不发送此标题、病历或照片。' },
    operations: { title: '集成与审计', description: '查看商业事件投递、死信恢复和访问审计。', events: 'Odoo 投递事件', audit: '操作审计', attempts: '尝试次数', reference: '商业引用', created: '创建时间', action: '操作', resource: '资源', actor: '操作者', retry: '重放死信', reason: '重放原因', retryPrompt: '修复上游问题后填写原因。同一事件编号保持不变。', summary: '当前门诊概览', patients: '患者档案', booked: '待到诊预约', drafts: '草稿病历' },
    state: { new: '新线索', contacted: '已联系', qualified: '已确认意向', won: '已成交', lost: '已结束', pending: '待处理', processing: '处理中', delivered: '已投递', dead_letter: '死信', booked: '已预约', arrived: '已到诊', completed: '已完成', cancelled: '已取消', no_show: '未到诊', done: '已完成', draft: '草稿', signed: '已签署', open: '开放' },
  },
  en: {
    orders: orderMessages.en,
    pagination: { previous: 'Previous', next: 'Next', page: 'Page {page}' },
    brand: 'Smilelab', tagline: 'Connecting clinics, clinicians and patients', workspace: 'DSO workspace', demo: 'Development demo · Use test data', loginTitle: 'Open your workspace', loginDescription: 'Use the separately supplied staff development credential.', identity: 'Demo account', staffKey: 'Staff development key', login: 'Sign in', logout: 'Sign out', language: '简体中文', clinic: 'Current clinic', refresh: 'Refresh', save: 'Save', create: 'Create', cancel: 'Cancel', close: 'Close', loading: 'Loading', empty: 'No records yet', error: 'Action could not be completed', networkError: 'Request failed. Check your connection and retry.', doctor: 'Clinician', manager: 'Clinic manager', consultant: 'Consultant', operator: 'Platform operator', nav: { orders: 'Shared orders', appointments: 'Appointments', patients: 'Patient records', crm: 'Consultations', operations: 'Integration & audit' },
    appointments: { tooMany: 'This date range has more than 1,000 appointments. Choose a shorter date view.', title: 'Appointments & availability', description: 'Review clinic appointments and manage bookable clinician slots.', newSlot: 'Add availability', start: 'Start time', end: 'End time', doctor: 'Clinician', patient: 'Patient', time: 'Appointment time', status: 'Status', action: 'Actions', slots: 'Bookable slots', schedule: 'Schedule calendar', arrive: 'Mark arrived', complete: 'Complete', noShow: 'Mark no-show', cancel: 'Cancel appointment', timezone: 'Times use your device timezone; submitted values include an offset.' },
    patients: { title: 'Patient records', description: 'Clinicians can access clinical data shared by their patients.', name: 'Name', created: 'Created', open: 'Open record', records: 'Clinical notes', newRecord: 'New note', complaint: 'Chief complaint', history: 'History', examination: 'Examination', assessment: 'Assessment', plan: 'Plan', draft: 'Draft', signed: 'Signed', sign: 'Sign note', signPrompt: 'Signed notes cannot be overwritten. Sign after checking the content.', amendment: 'Create amendment', edit: 'Edit draft', teeth: 'Tooth chart (FDI)', permanent: 'Permanent', primary: 'Primary', tooth: 'Tooth', finding: 'Tooth note', removeTooth: 'Remove tooth note', noAccess: 'Your role can access the directory. Clinical data requires clinician permissions and patient consent.', select: 'Select a patient from the directory', previous: 'Amends original record', version: 'Version', recordsDescription: 'Amend signed notes with a new record, retaining the original.' },
    crm: { title: 'Consultations & follow-up', description: 'Track dental consultation opportunities and follow-up separately from clinical notes.', newLead: 'New opportunity', titleField: 'Opportunity title', stage: 'Stage', created: 'Created', open: 'Open follow-up', activities: 'Follow-up activities', newActivity: 'Add follow-up', summary: 'Summary', due: 'Due time', type: 'Type', finish: 'Complete activity', call: 'Call', follow_up: 'Follow-up', visit: 'Visit', boundary: 'Commercial integration sends a generated reference, excluding this title, clinical notes and photos.' },
    operations: { title: 'Integration & audit', description: 'Inspect commercial deliveries, recover dead letters and review access events.', events: 'Odoo deliveries', audit: 'Audit events', attempts: 'Attempts', reference: 'Commercial reference', created: 'Created', action: 'Action', resource: 'Resource', actor: 'Actor', retry: 'Replay dead letter', reason: 'Reason for replay', retryPrompt: 'Fix the upstream issue, then record a reason. The event ID remains unchanged.', summary: 'Current clinic overview', patients: 'Patient profiles', booked: 'Booked appointments', drafts: 'Draft notes' },
    state: { new: 'New', contacted: 'Contacted', qualified: 'Qualified', won: 'Won', lost: 'Closed', pending: 'Pending', processing: 'Processing', delivered: 'Delivered', dead_letter: 'Dead letter', booked: 'Booked', arrived: 'Arrived', completed: 'Completed', cancelled: 'Cancelled', no_show: 'No-show', done: 'Done', draft: 'Draft', signed: 'Signed', open: 'Open' },
  },
};
export const i18n = createI18n({ legacy: false, locale: 'zh-Hans', fallbackLocale: 'en', messages });
