// 订单各角色共用进度名称；仅配置中文与英文。
export const orderMessages = {
  'zh-Hans': {
    title: '共享订单', description: '患者、医生、销售、制造和质检查看同一订单进度。', create: '发起申请', open: '查看进度', product: '产品', quantity: '数量', request: '申请说明', recipient: '收货人', phone: '联系电话', address: '收货地址', doctor: '审核医生', amount: '订单金额', reference: '订单编号', status: '当前进度', next: '下一责任人', timeline: '订单历程', select: '选择一笔订单查看完整进度', specification: '医生确认的制造要求', batch: '生产批次', carrier: '承运商', tracking: '物流单号', reason: '原因（仅填写本次操作相关信息）', checks: '质检清单', identity: '订单与产品身份一致', specificationCheck: '符合批准制造要求', finish: '产品外观与完成度合格', packaging: '包装与标识合格', payment: '模拟付款凭证', demo: '演示付款，不扣款，不产生真实交易。价格为演示目录价格。', authority: '订单状态由平台统一维护', synchronized: '自动刷新进度（每5秒）', confirm: '确认操作', version: '版本', loginPatient: '患者（演示）', sales: '订单销售', manufacturer: '制造人员', quality: '独立质检', patientCode: '患者测试标识', devKey: '患者开发密钥', missing: '请填写必填信息', roles: { patient: '患者', doctor: '医生', sales: '销售', manufacturer: '制造', quality: '质检', none: '已结束' }, states: { requested: '待医生审核', pending_payment: '待患者付款', paid: '已付款，待销售验证', sales_validated: '待制造验证', manufacturing_ready: '制造已验证，待开工', manufacturing: '生产中', qa_pending: '待质检', rework_required: '质检未通过，待返工', qa_passed: '质检通过，待发货', shipped: '已发货，待签收', delivered: '已签收', rejected: '医生未批准', cancelled: '已取消' }, actions: { request: '患者发起申请', doctor_approve: '医生批准申请', doctor_reject: '医生拒绝申请', pay_demo: '确认模拟付款', sales_validate: '销售验证订单', manufacturer_validate: '制造验证订单', start_manufacturing: '开始生产 / 返工', finish_manufacturing: '生产完成，提交质检', qa_pass: '质检通过', qa_fail: '质检不通过，退回返工', ship: '登记发货', confirm_delivery: '确认收货', cancel: '取消未付款订单' }, products: { retainer_upper: '上颌保持器（演示）', retainer_lower: '下颌保持器（演示）', retainer_pair: '上下颌保持器（演示）' },
  },
  en: {
    title: 'Shared orders', description: 'Patients, clinicians, sales, production and QA share one order timeline.', create: 'Request an order', open: 'View progress', product: 'Product', quantity: 'Quantity', request: 'Request details', recipient: 'Recipient', phone: 'Contact number', address: 'Delivery address', doctor: 'Reviewing clinician', amount: 'Order amount', reference: 'Order reference', status: 'Current progress', next: 'Next responsible role', timeline: 'Order timeline', select: 'Select an order to see its complete progress', specification: 'Clinician-approved production specification', batch: 'Production batch', carrier: 'Carrier', tracking: 'Tracking number', reason: 'Reason (information relevant to this action only)', checks: 'QA checklist', identity: 'Order and product identity match', specificationCheck: 'Meets approved specification', finish: 'Product finish passes inspection', packaging: 'Packaging and labels pass inspection', payment: 'Simulated payment receipt', demo: 'Simulated payment: no money is collected. Prices are for demonstration.', authority: 'The platform maintains the authoritative order state', synchronized: 'Progress refreshes every 5 seconds', confirm: 'Confirm action', version: 'Version', loginPatient: 'Patient (demo)', sales: 'Order sales', manufacturer: 'Production staff', quality: 'Independent QA', patientCode: 'Patient test identifier', devKey: 'Patient development key', missing: 'Complete the required fields', roles: { patient: 'Patient', doctor: 'Clinician', sales: 'Sales', manufacturer: 'Production', quality: 'QA', none: 'Complete' }, states: { requested: 'Awaiting clinician review', pending_payment: 'Awaiting patient payment', paid: 'Paid; awaiting sales validation', sales_validated: 'Awaiting production validation', manufacturing_ready: 'Validated; ready to manufacture', manufacturing: 'Manufacturing', qa_pending: 'Awaiting QA', rework_required: 'QA failed; rework required', qa_passed: 'QA passed; ready to ship', shipped: 'Shipped; awaiting receipt', delivered: 'Delivered', rejected: 'Clinician rejected', cancelled: 'Cancelled' }, actions: { request: 'Patient requested order', doctor_approve: 'Approve request', doctor_reject: 'Reject request', pay_demo: 'Confirm simulated payment', sales_validate: 'Validate sales order', manufacturer_validate: 'Validate production order', start_manufacturing: 'Start manufacture / rework', finish_manufacturing: 'Finish production; submit to QA', qa_pass: 'Pass QA', qa_fail: 'Fail QA; return for rework', ship: 'Register shipment', confirm_delivery: 'Confirm receipt', cancel: 'Cancel unpaid order' }, products: { retainer_upper: 'Upper retainer (demo)', retainer_lower: 'Lower retainer (demo)', retainer_pair: 'Upper and lower retainers (demo)' },
  },
};
